### ISSUE TITLE
Bonemealing sugar cane is very slow/not working

### ISSUE THREAD

**Issue by redcreeper14385** [redcreeper14385/moundertweaks#11]
Bonemealing cactus and nether wart works fine, but sugar cane is incredibly slow and might not be working at all, even with the config turned up. @BoogieMonster1O1 is looking into this.

**Comment by mschae23** [comment]
`        if (block == Blocks.CACTUS && new Random().nextInt(128) <= Math.toIntExact(MounderTweaksMain.CONFIG.common.bonemeal.sugarCaneChance)) {`
Shouldn't that be `Blocks.SUGAR_CANE`?

**Comment by redcreeper14385** [comment]
Ah, thanks very much! I'll get this sorted ASAP.

**Comment by redcreeper14385** [comment]
Reopening, will close when fixed.
